spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL}
    hikari:
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

remittance:
  secret-key: ${SECRET_KEY}

server:
  port: ${API_PORT}